FROM mysql:latest

RUN chown -R mysql:root /var/lib/mysql/

COPY ./db.vol/db.conf/mysqld.cnf etc/mysql/conf.d

#RUN sed -i 's/MYSQL_DATABASE/'$MYSQL_DATABASE'/g' /etc/mysql/data.sql
#RUN cp /etc/mysql/data.sql /docker-entrypoint-initdb.d

RUN mysql -u root -e "UPDATE mysql.user SET host='%' WHERE host='database';"
EXPOSE 3306 33060