FROM mysql:latest

RUN chown -R mysql:root /var/lib/mysql/

COPY ./db.vol/db.conf/mysqld.cnf etc/mysql/conf.d


EXPOSE 3306 33060

RUN chmod -R 755 /var/run/mysqld/ .
RUN mysql -u root -e "UPDATE mysql.user SET host='%' WHERE host='database';"