FROM mysql:latest


RUN chown -R mysql:root /var/lib/mysql/
COPY ./db.vol/db.conf/mysqld.cnf etc/mysql/conf.d

COPY ./db.vol/db/docker-entrypoint.sh docker-entrypoint-initdb.d
RUN chmod 777 docker-entrypoint-initdb.d/docker-entrypoint.sh